bfb-build: Restart systemd-binfmt if configuration changed
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/bfb-build b/bfb-build
--- a/bfb-build
+++ b/bfb-build
@@ -28,10 +28,15 @@ fi
 IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
 
 if [ "`uname -m`" != "aarch64" ]; then
+	if [ ! -d /etc/binfmt.d ]; then
+		echo "ERROR: systemd package is required"
+		exit 1
+	fi
 	if ! (grep -q /usr/bin/qemu-aarch64-static /etc/binfmt.d/qemu-aarch64.conf > /dev/null 2>&1); then
 		cat > /etc/binfmt.d/qemu-aarch64.conf << EOF
 :qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7:\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-aarch64-static:
 EOF
+		systemctl restart systemd-binfmt
 	fi
 fi
 
