bf-bundle-2.7.0-31_24.04_ubuntu-20.04
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/ubuntu/20.04/Dockerfile b/ubuntu/20.04/Dockerfile
--- a/ubuntu/20.04/Dockerfile
+++ b/ubuntu/20.04/Dockerfile
@@ -3,6 +3,11 @@ FROM scratch
 ADD ubuntu-20.04-server-cloudimg-arm64-root.tar.xz /
 ADD qemu-aarch64-static /usr/bin/
 
+ARG BASE_URL
+ARG DOCA_VERSION
+ARG BSP_VERSION
+ARG DISTRO
+ARG DISTRO_VERSION
 ARG MLNX_FW_UPDATER=mlnx-fw-updater-signed
 WORKDIR /root/workspace
 ADD install.sh .
@@ -10,7 +15,6 @@ ADD install.env ./install.env
 ADD create_bfb .
 ADD build_ubuntu_bfb .
 ADD mlxbf-bootimages.deb .
-ADD doca-repo.deb .
 ADD BF2BMC ./BF2BMC
 ADD BF3BMC ./BF3BMC
 
@@ -22,17 +26,28 @@ ENV RUN_FW_UPDATER=no
 RUN mkdir -p /run/systemd; echo docker > /run/systemd/container
 
 RUN apt update
+RUN apt upgrade -y
 RUN apt remove --purge -y snapd plymouth
 RUN apt autoremove -y
-RUN apt install -y grub-efi-arm64-signed grub-efi-arm64-bin shim-signed watchdog binutils sbsigntool rasdaemon net-tools nfs-common iptables-persistent rsync tcpdump nvme-cli iputils-arping iputils-ping iputils-tracepath bridge-utils iperf3 bc lm-sensors ifenslave acpid network-manager kexec-tools i2c-tools dc lldpad unzip sysstat mmc-utils uuid ntp jq libev4 conntrack
+RUN apt install -y watchdog binutils sbsigntool rasdaemon net-tools nfs-common iptables-persistent rsync tcpdump nvme-cli iputils-arping iputils-ping iputils-tracepath bridge-utils iperf3 bc lm-sensors ifenslave acpid network-manager kexec-tools i2c-tools dc lldpad unzip sysstat mmc-utils uuid uuid-runtime ntp jq libev4 conntrack sshpass dracut dracut-network perl-modules wget
 # Install ipmitool and ignore default OpenIPMI due to possible conflicts with mlx-openipmi (notice the - in openipmi-)
 # Ref: https://serverfault.com/questions/250224/how-do-i-get-apt-get-to-ignore-some-dependencies
 RUN apt install -y ipmitool openipmi-
 RUN apt install -y docker.io; systemctl disable docker.service || true; systemctl disable docker.socket || true
 RUN apt install -y python3-pip
 RUN apt install -y build-essential
-RUN apt install -y libpam-pwquality; echo "minlen = 8" >> /etc/security/pwquality.conf; echo "minclass = 3" >> /etc/security/pwquality.conf
+RUN apt install -y libpam-pwquality; \
+	sed -i -r -e "s/# minlen =.*/minlen = 12/" /etc/security/pwquality.conf; \
+	sed -i -e '/use_authtok/ipassword\trequired\t\t\tpam_pwhistory.so  remember=3' /etc/pam.d/common-password; \
+	sed -i -r -e "s/# silent/silent/;s/# deny.*/deny = 10/;s/# unlock_time.*/unlock_time = 600/" /etc/security/faillock.conf
 RUN apt install -y python2.7 python3.8 python3-pyinotify
+
+#line below was commented out due to missmatch between versions coming from focal-proposed
+#RUN echo 'deb http://ports.ubuntu.com/ubuntu-ports focal-proposed main restricted universe multiverse' >> /etc/apt/sources.list
+RUN apt update
+RUN apt install -y grub-efi-arm64-signed grub-efi-arm64-bin shim-signed
+RUN perl -ni -e 'print unless /focal-proposed/' /etc/apt/sources.list
+RUN apt update
 
 # Grub password
 RUN echo 'set superusers="admin"' >> /etc/grub.d/40_custom; \
@@ -44,52 +59,52 @@ RUN echo 'set superusers="admin"' >> /etc/grub.d/40_custom; \
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python2.7 10
 
-RUN wget -qO - https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/kubernetes-archive-keyring.gpg add -
-RUN echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
+RUN mkdir -p -m 755 /etc/apt/keyrings/
+RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
+RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
+
+RUN curl -fsSL https://linux.mellanox.com/public/repo/doca/GPG-KEY-Mellanox.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/GPG-KEY-Mellanox.pub
+
 RUN apt update
 # Install Libvirt+QEMU+KVM
 RUN apt install -y bridge-utils cpu-checker libvirt-clients libvirt-daemon qemu qemu-kvm
-RUN apt install -y kubelet=1.25.3-00 runc containerd cri-tools=1.25.0-00 kubernetes-cni=1.1.1-00
-RUN apt-mark hold kubelet cri-tools kubernetes-cni
 RUN apt upgrade -y
-RUN wget -qO - @BASE_URL@/doca/@DOCA_VERSION@/ubuntu20.04/aarch64/GPG-KEY-Mellanox.pub | sudo apt-key add -
-RUN echo "deb [trusted=yes] @BASE_URL@/doca/@DOCA_VERSION@/ubuntu20.04/\$(ARCH) ./" | tee /etc/apt/sources.list.d/doca.tmp.list
-RUN dpkg -i /root/workspace/doca-repo.deb
-RUN apt update || true
-RUN dpkg -i /var/doca-dpu-repo-ubuntu2004-local/*mstflint*.deb || true
+RUN apt install -y runc containerd kubelet=1.29.3-1.1 kubernetes-cni=1.3.0-1.1 cri-tools=1.29.0-1.1 kubeadm=1.29.3-1.1
+RUN rm -f /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
+RUN apt-mark hold kubelet cri-tools kubernetes-cni kubeadm
+RUN echo "deb [trusted=yes] ${BASE_URL}/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/arm64-dpu/ /" | sudo tee /etc/apt/sources.list.d/doca.base.list
+RUN apt update
+RUN apt install -y mstflint=4.26.0-1
+
 RUN apt-mark hold mstflint
 RUN apt install -y -f $MLNX_FW_UPDATER
 
 RUN apt install -y -f \
-	linux-bluefield=5.4.0.1078.73 \
-	linux-bluefield-headers-5.4.0-1078=5.4.0-1078.84 \
-	linux-bluefield-tools-5.4.0-1078=5.4.0-1078.84 \
-	linux-headers-5.4.0-1078-bluefield=5.4.0-1078.84 \
-	linux-headers-bluefield=5.4.0.1078.73 \
-	linux-image-5.4.0-1078-bluefield=5.4.0-1078.84 \
-	linux-image-bluefield=5.4.0.1078.73 \
-	linux-modules-5.4.0-1078-bluefield=5.4.0-1078.84 \
-	linux-tools-5.4.0-1078-bluefield=5.4.0-1078.84 \
-	linux-tools-bluefield=5.4.0.1078.73 \
+	linux-bluefield=5.4.0.1084.80 \
+	linux-bluefield-headers-5.4.0-1084=5.4.0-1084.91 \
+	linux-bluefield-tools-5.4.0-1084=5.4.0-1084.91 \
+	linux-headers-5.4.0-1084-bluefield=5.4.0-1084.91 \
+	linux-headers-bluefield=5.4.0.1084.80 \
+	linux-image-5.4.0-1084-bluefield=5.4.0-1084.91 \
+	linux-image-bluefield=5.4.0.1084.80 \
+	linux-modules-5.4.0-1084-bluefield=5.4.0-1084.91 \
+	linux-tools-5.4.0-1084-bluefield=5.4.0-1084.91 \
+	linux-tools-bluefield=5.4.0.1084.80 \
 	linux-libc-dev:arm64 \
 	linux-tools-common
 
 
-RUN apt install -y -f doca-runtime doca-tools doca-sdk || true
+RUN dpkg -i /root/workspace/mlxbf-bootimages*.deb
+RUN apt install -y -f doca-runtime doca-devel || true
 RUN apt install -y -f mlnx-snap || true
-RUN cd /var/doca-dpu-repo-ubuntu2004-local; for dr in *modules*deb; do dpkg -i $dr || true;done
-RUN apt remove --purge -y doca-dpu-repo-ubuntu2004-local || true
+RUN apt install -y gpio-mlxbf-modules gpio-mlxbf2-modules gpio-mlxbf3-modules i2c-mlxbf-modules mlxbf-gige-modules mlxbf-livefish-modules mlxbf-pka-modules mlxbf-pmc-modules mlxbf-ptm-modules mlxbf-tmfifo-modules pwr-mlxbf-modules
+
 RUN apt --fix-broken install -y || true
 RUN apt-mark hold linux-tools-bluefield linux-image-bluefield linux-bluefield linux-headers-bluefield linux-image-bluefield linux-libc-dev linux-tools-common
 RUN apt --fix-broken install -y || true
-RUN /bin/rm -f /etc/apt/sources.list.d/doca.tmp.list
 RUN apt update || true
 RUN /usr/sbin/dpkg-reconfigure bf-release || true
-RUN apt clean
-RUN rm -rf /var/lib/apt/lists/*
 RUN mkdir -p /etc/kubelet.d
-RUN mkdir -p /workspace
-RUN dpkg -i /root/workspace/mlxbf-bootimages*.deb
 
 # Manage system services
 RUN systemctl disable mlx-regex.service || true
@@ -111,7 +126,6 @@ RUN systemctl disable docker.service || true
 RUN systemctl disable docker.socket || true
 RUN systemctl disable kubelet.service || true
 RUN systemctl disable containerd.service || true
-RUN systemctl disable mosquitto.service || true
 
 RUN /usr/sbin/update-pciids || true
 
diff --git a/ubuntu/20.04/create_bfb b/ubuntu/20.04/create_bfb
--- a/ubuntu/20.04/create_bfb
+++ b/ubuntu/20.04/create_bfb
@@ -121,17 +121,30 @@ ex()
 	fi
 }
 
-/usr/sbin/update-initramfs -u -k $kernel
-
 ex mkdir -p ${WDIR}
 ex cd ${WDIR}
 ex rm -rf initramfs
 
 initramfs=/boot/initrd.img-$kernel
 initramfs=$(realpath $initramfs)
-# ex mkinitramfs -o $WDIR/dump-initramfs-v0 $kernel
-cp $initramfs $WDIR/dump-initramfs-v0
 initramfs=$WDIR/dump-initramfs-v0
+
+ADD_DRIVERS=""
+for mod in mlxbf-bootctl sdhci-of-dwcmshc mlxbf-tmfifo dw_mmc-bluefield mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q
+do
+	if (modinfo -k $kernel $mod 2>/dev/null | grep "filename:" | grep -q builtin); then
+		continue
+	fi
+	if ! (modinfo -k $kernel $mod 2>/dev/null); then
+		continue
+	fi
+	ADD_DRIVERS="$ADD_DRIVERS $mod"
+done
+
+dracut --no-hostonly -m "bash network base systemd systemd-initrd systemd-networkd dracut-systemd shutdown udev-rules" \
+    --install "/etc/udev/rules.d/91-tmfifo_net.rules /etc/udev/rules.d/92-oob_net.rules" \
+    --add-drivers "${ADD_DRIVERS}" \
+    --gzip $initramfs ${kernel}
 
 case "$(file --brief --mime-type "$initramfs")" in
 	"application/x-lzma")
@@ -150,9 +163,9 @@ mkdir -p ${WDIR}/initramfs
 cd initramfs
 $cat_initrd "$initramfs" | sudo cpio -i
 
-copy_bin()
+copy_file()
 {
-	if [ -e $1 ]; then
+	if [[ -e $1 || -h $1 ]]; then
 		bin=$1
 	else
 		bin=$(which $1 2> /dev/null)
@@ -216,43 +229,60 @@ copy_module()
 }
 
 (cd usr/bin; sudo ln -s xz xzcat)
+cp $(readlink -f /usr/bin/which) ./usr/bin/which
 
-for tool in $(dpkg -L mlxbf-scripts | grep bin/) \
-		$(dpkg -L dosfstools | grep -v share) \
-		$(dpkg -L e2fsprogs | grep -v share) \
-		$(dpkg -L fdisk | grep -v share) \
-		$(dpkg -L kmod | grep -v share) \
-		$(dpkg -L pciutils | grep -v share) \
-		$(dpkg -L usbutils | grep -v share) \
-		$(dpkg -L mft) \
-		$(dpkg -L mft-oem) \
-		$(dpkg -L kernel-mft-modules) \
-		$(dpkg -L tar | grep -v share) \
-		xz efibootmgr bash getopt hexdump mstflint lspci perl \
+for tool in xz efibootmgr bash getopt hexdump mstflint lspci \
 		lsblk watchdog shutdown systemctl strings aarch64-linux-gnu-strings \
-		mlxbf-bootctl id dirname curl openssl parted jq $ADDON_TOOLS
+		mlxbf-bootctl id dirname curl openssl parted jq mlnx_bf_configure $ADDON_TOOLS
 do
 	if [ -d $tool ]; then
 		continue
 	fi
 	# Remove tools coming with busybox
 	/bin/rm -f .${tool}
-	copy_bin $tool
+	copy_file $tool
 done
 
-for deb in coreutils nvme-cli mmc-utils iputils-ping uuid-runtime sshpass openssh-client util-linux $ADDON_DEBS
+libperl=$(dpkg -S /usr/lib/aarch64-linux-gnu/perl | cut -d ':' -f 1 | tr -d ',')
+perl_modules=$(dpkg -S /usr/share/perl | cut -d ':' -f 1 | tr -d ',')
+python3=$(dpkg -S /usr/bin/pdb3.* | head -1 | cut -d ':' -f 1 | tr -d ',')
+libpython3_minimal=$(dpkg -S /usr/lib/python3*/os.py | head -1 | cut -d ':' -f 1 | tr -d ',')
+libpython3=$(dpkg -S /usr/lib/aarch64-linux-gnu/libpython3.*.so.1 | head -1 | cut -d ':' -f 1 | tr -d ',')
+python3_distutils=$(dpkg -S /usr/lib/python3.*/distutils | head -1 | cut -d ':' -f 1 | tr -d ',')
+python3_lib2to3=$(dpkg -S /usr/lib/python3.*/lib2to3 | head -1 | cut -d ':' -f 1 | tr -d ',')
+
+for deb in mlxbf-scripts mft mft-oem dosfstools e2fsprogs fdisk kmod pciutils \
+		   usbutils tar coreutils nvme-cli mmc-utils iputils-ping uuid-runtime \
+		   sshpass openssh-client util-linux ipmitool procps debianutils \
+		   iproute2 findutils perl-base $libperl $perl_modules \
+		   $libpython3_minimal $python3_distutils $python3_lib2to3 $python3 \
+		   $libpython3 bsdutils libexpat1 wget $ADDON_DEBS
 do
-	for tool in $(dpkg -L $deb | grep -v share)
+	for pfile in $(dpkg -L $deb)
 	do
-		if [ -d $tool ]; then
+		case "$pfile" in
+			*man*|*doc*)
+				continue
+				;;
+			*share*)
+				case "$deb" in
+					perl*|mft*)
+						;;
+					*)
+						continue
+						;;
+				esac
+				;;
+		esac
+		if [[ -d $pfile && ! -h $pfile ]]; then
 			continue
 		fi
-		/bin/rm -f .${tool}
-		copy_bin $tool
+		/bin/rm -f .${pfile}
+		copy_file $pfile
 	done
 done
 
-for mod in mlxbf_tmfifo dw_mmc-bluefield dw_mmc dw_mmc-pltfm mmc_block sdhci sdhci-of-dwcmshc nvme-rdma nvme-tcp nvme mlx5_ib mlxfw ib_umad ib_ipoib ib_iser mst_pci mst_pciconf $ADDON_KERNEL_MODULES
+for mod in mlxbf_tmfifo dw_mmc-bluefield dw_mmc dw_mmc-pltfm mmc_block sdhci sdhci-of-dwcmshc nvme-rdma nvme-tcp nvme mlx5_ib mlxfw ib_umad ib_ipoib ib_iser mst_pci mst_pciconf bf3_livefish ipmi_devintf ipmb_host ipmi_ssif i2c-mlxbf nls_iso8859-1 $ADDON_KERNEL_MODULES
 do
 	copy_module $mod
 done
@@ -261,6 +291,10 @@ sudo depmod -a -b ./ $kernel
 sudo mkdir -p usr/share/misc/ bin/ var/log/watchdog
 sudo cp /usr/share/misc/pci.ids usr/share/misc/
 sudo cp /etc/watchdog.conf etc
+if ! [ -e usr/bin/python ]; then
+	ln -s python3.10 usr/bin/python
+fi
+
 # Make sure we can load mlx-bootctl
 bootctl_ko=""
 for driver in mlxbf-bootctl mlx-bootctl
@@ -289,22 +323,24 @@ sudo mkdir -p mnt
 
 if [ -d ${SDIR}/BF3BMC/ ]; then
 	/bin/rm -rf BF3BMC
-	if (grep -q prod /etc/mlnx-release); then
-		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
-	elif (grep -q dev /etc/mlnx-release); then
-		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	if (grep -q prod /etc/mlnx-release) && [ -d ${SDIR}/BF3BMC/pk ]; then
+		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC
+	elif (grep -q dev /etc/mlnx-release) && [ -d ${SDIR}/BF3BMC/dk ]; then
+		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC
+	elif [ -d ${SDIR}/BF3BMC/qp ]; then
+		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC
 	else
-		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+		echo "WARNING: BF3 BMC Software was not found"
 	fi
-	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC
+	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC || echo "WARNING: BF3 Golden Images for BMC were not found"
 fi
 
 if [ -d ${SDIR}/BF2BMC/ ]; then
 	/bin/rm -rf BF2BMC
 	if (grep -q prod /etc/mlnx-release); then
-		cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+		[ -d ${SDIR}/BF2BMC/pk ] && cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || echo "WARNING: BF2 BMC Software was not found"
 	else
-		cp -a ${SDIR}/BF2BMC/qp/ ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+		[ -d ${SDIR}/BF2BMC/qp ] && cp -a ${SDIR}/BF2BMC/qp ./BF2BMC || echo "WARNING: BF2 BMC Software was not found"
 	fi
 fi
 
@@ -314,17 +350,22 @@ XZ_OPT="--threads=0 -9 --verbose" tar -cJp --exclude='./workspace' --exclude='./
 ex install -m 0755 ${SDIR}/install.sh ./ubuntu/install.sh
 ex cp -a ${SDIR}/install.env ./ubuntu/
 
+mkdir -p scripts
 cat > scripts/initrd-install << EOF
 #!/bin/bash
 
 printf_msg()
 {
-	echo "$@" | tee /dev/kmsg
+	echo "\$@" > /dev/kmsg
 	return 0
 }
 
+modprobe nls_iso8859-1 > /dev/null 2>&1
 modprobe -a sdhci-of-dwcmshc dw_mmc-bluefield > /dev/null 2>&1
 modprobe mlxbf_tmfifo > /dev/null 2>&1
+modprobe -a ipmi_msghandler ipmi_devintf i2c-mlxbf
+modprobe ipmb_host slave_add=0x10
+echo ipmb-host 0x1011 > /sys/bus/i2c/devices/i2c-1/new_device
 modprobe -a mlx5_ib mlxfw ib_umad
 modprobe nvme > /dev/null 2>&1
 insmod /mlx-bootctl.ko > /dev/null 2>&1
@@ -351,9 +392,23 @@ EOF
 
 chmod +x scripts/initrd-install
 sudo rm -f conf/conf.d/ubuntu-core*
-sudo sh -c 'echo "BOOT=initrd-install" > conf/conf.d/initrd_install'
-sudo sh -c 'echo "ROOT=\"LABEL=writable\"" > conf/conf.d/default_root'
 
+cat > usr/lib/systemd/system/install-ubuntu.service << EOF
+[Unit]
+Description=Install ubuntu Linux
+After=initrd-root-fs.target initrd-parse-etc.service
+After=dracut-initqueue.service dracut-mount.service
+
+[Service]
+Type=oneshot
+ExecStart=/scripts/initrd-install
+StandardInput=null
+StandardOutput=syslog
+StandardError=syslog+console
+EOF
+
+mkdir -p etc/systemd/system/initrd.target.wants
+ln -s /usr/lib/systemd/system/install-ubuntu.service etc/systemd/system/initrd.target.wants/install-ubuntu.service
 
 # Make initramfs with new ubuntu
 find . -print0 | sudo cpio --null -o --format=newc | gzip -9 > "$initramfs"
