bf-bundle-2.9.4-38_25.12_debian-12_5.15
Signed-off-by: Moshe Sheena <msheena@nvidia.com>

diff --git a/common/install.env/common b/common/install.env/common
--- a/common/install.env/common
+++ b/common/install.env/common
@@ -15,6 +15,7 @@ dpu_part_number=$(mstflint -d $cx_pcidev q full | grep "Part Number:" | awk '{pr
 PSID=$(mstflint -d $cx_pcidev q | grep PSID | awk '{print $NF}')
 BD_PSIDS=${BD_PSIDS:-"BD_0000000004 BD_0000000005"}
 DEVICE_TIMEOUT=${DEVICE_TIMEOUT:-30}
+FSTAB_USE_DEV_NAME=${FSTAB_USE_DEV_NAME:-"no"}
 
 rlog()
 {
@@ -41,7 +42,7 @@ log()
 fail()
 {
 	log "$@"
-	log "Installation failed"
+	log "ERR Installation failed"
 	sleep 3
 	reboot -f
 }
@@ -220,6 +221,24 @@ upgrade_emmc_fw()
 		return
 	fi
 
+	ilog "Unmount any partitions on mmcblk0"
+	for p in /dev/mmcblk0p*i
+	do
+		[ -e "$p" ] || continue
+		if findmnt -rn "$p" >/dev/null 2>&1; then
+			ilog "Unmounting $p"
+			umount -R "$p" || ilog "WARN: umount $p failed"
+		fi
+	done
+	sync
+
+	ilog "Setting /dev/mmcblk0 read-only"
+	blockdev --setro /dev/mmcblk0 || ilog "WARN: setro failed"
+
+	ilog "Pausing udev rule execution"
+	udevadm control --stop-exec-queue || true
+	trap 'udevadm control --start-exec-queue || true' EXIT
+
 	# Update eMMC Firmware
 	cmd="mmc ffu $EMMC_SWISSBIT_FIRMWARE /dev/mmcblk0"
 	ilog "Runnning: $cmd"
@@ -228,7 +247,6 @@ upgrade_emmc_fw()
 	ilog "$output"
 	if [ $rc -eq 0 ]; then
 		ilog "eMMC Firmware was updated successfully"
-		ilog "A system power cycle is required to apply the new eMMC firmware"
 		sync
 		rmmod sdhci_of_dwcmshc
 		modprobe sdhci_of_dwcmshc
@@ -480,11 +498,19 @@ configure_target_os()
 	BOOT_LABEL=${device}p2
 	BOOT_EFI_LABEL=${device}p1
 
-	cat > /mnt/etc/fstab << EOF
+	if [ "${FSTAB_USE_DEV_NAME}" == "yes" ]; then
+		cat > /mnt/etc/fstab << EOF
+$ROOT_LABEL  /           ${ROOTFS}     defaults                   0 1
+$BOOT_LABEL  /boot       ${ROOTFS}     defaults                   0 2
+$BOOT_EFI_LABEL  /boot/efi   vfat    umask=0077,shortname=winnt 0 2
+EOF
+	else
+		cat > /mnt/etc/fstab << EOF
 $(get_part_id $ROOT_LABEL)  /           ${ROOTFS}     defaults                   0 1
 $(get_part_id $BOOT_LABEL)  /boot       ${ROOTFS}     defaults                   0 2
 $(get_part_id $BOOT_EFI_LABEL)  /boot/efi   vfat    umask=0077,shortname=winnt 0 2
 EOF
+	fi
 
 	memtotal=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
 	if [ $memtotal -gt 16000000 ]; then
