bf-bundle-2.9.3-31_25.06_anolis-8.6
Signed-off-by: Moshe Sheena <msheena@nvidia.com>

diff --git a/common/install.env/nic-fw b/common/install.env/nic-fw
--- a/common/install.env/nic-fw
+++ b/common/install.env/nic-fw
@@ -1,23 +1,35 @@
 NIC_FW_UPDATE_DONE=0
 FORCE_NIC_FW_UPDATE=${FORCE_NIC_FW_UPDATE:-"no"}
+NIC_FW_RESET=${NIC_FW_RESET:-"yes"}
+FORCE_NIC_FW_RESET=${FORCE_NIC_FW_RESET:-"no"}
 NIC_FW_RESET_REQUIRED=0
 NIC_FW_FOUND=0
 FW_UPDATER=/opt/mellanox/mlnx-fw-updater/mlnx_fw_updater.pl
 FW_DIR=/opt/mellanox/mlnx-fw-updater/firmware/
 is_nic_mode=${is_nic_mode:-0}
 NIC_FW_EXTRACTION_DONE=0
+PROVIDED_NIC_FW_VERSION=""
 
 CHROOT=
+FLINT=mstflint
+if [ -x /usr/bin/flint ]; then
+	FLINT=/usr/bin/flint
+fi
+
+if [ "$FORCE_NIC_FW_RESET" == "yes" ]; then
+	NIC_FW_RESET="yes"
+fi
 
 running_nic_fw()
 {
-	mstflint -d $cx_pcidev q 2>&1 | grep -w 'FW Version:' | awk '{print $NF}'
+	$FLINT -d $cx_pcidev q 2>&1 | grep -w 'FW Version:' | awk '{print $NF}'
 }
 
 provided_nic_fw()
 {
 	if [ ! -z "${PSID}" ]; then
-		$CHROOT ${FW_DIR}/mlxfwmanager_sriov_dis_aarch64_${cx_dev_id} --list 2> /dev/null | grep -w "${PSID}" | awk '{print $4}'
+		PROVIDED_NIC_FW_VERSION=$($CHROOT ${FW_DIR}/mlxfwmanager_sriov_dis_aarch64_${cx_dev_id} --list 2> /dev/null | grep -w "${PSID}" | awk '{print $4}')
+		echo $PROVIDED_NIC_FW_VERSION
 	fi
 }
 
@@ -55,6 +67,12 @@ fw_update()
 	fi
 
 	if [ $NIC_FW_FOUND -eq 1 ]; then
+		# Check if firmware image was already updated on flash
+		if ($FLINT -d $cx_pcidev q 2>&1 | grep -q 'FW Version(Running)'); then
+			log "INFO: Reactivating previous firmware image on the NIC"
+			ilog "$($FLINT -d $cx_pcidev ir)"
+		fi
+
 		if [ "$(running_nic_fw)" == "$(provided_nic_fw)" ]; then
 			if [ "${FORCE_NIC_FW_UPDATE}" == "yes" ]; then
 				log "INFO: Installed NIC Firmware is the same as provided. FORCE_NIC_FW_UPDATE is set."
@@ -80,16 +98,19 @@ fw_update()
 			cat /tmp/mlnx_fw_update.log > /dev/ttyAMA0
 			cat /tmp/mlnx_fw_update.log >> $LOG
 		fi
+		NIC_FW_UPDATE_DONE=1
 		if [ $rc -ne 0 ] || (grep -q '\-E- Failed' /tmp/mlnx_fw_update.log); then
 			NIC_FW_UPDATE_PASSED=0
 			log "INFO: NIC firmware update failed"
+			return 1
 		else
 			NIC_FW_UPDATE_PASSED=1
 			log "INFO: NIC firmware update done: $(provided_nic_fw)"
+			return 0
 		fi
-		NIC_FW_UPDATE_DONE=1
 	else
 		log "WARNING: NIC Firmware files were not found"
+		return 1
 	fi
 }
 
@@ -98,6 +119,28 @@ fw_reset()
 	if [ $is_nic_mode -eq 1 ]; then
 		log "Run mlxfwreset or system-level reset to load new NIC firmware"
 		return
+	fi
+
+	if ($CHROOT mlxfwreset -d /dev/mst/mt*_pciconf0 q | grep live-Patch | grep -qw "\-Supported"); then
+		log "INFO: Live Patch NIC Firmware reset is supported."
+		msg=$($CHROOT mlxfwreset -d /dev/mst/mt*_pciconf0 -y -l 0 r 2>&1)
+		if [ $? -ne 0 ]; then
+			log "INFO: Live Patch NIC Firmware reset failed."
+			log "INFO: $msg"
+			if [ "$FORCE_NIC_FW_RESET" != "yes" ]; then
+				return
+			fi
+		else
+			log "INFO: Live Patch NIC Firmware reset done"
+			return
+		fi
+	else
+		if [ "$LFWP" == "yes" ]; then
+			log "INFO: Live Patch NIC Firmware reset is not supported."
+			if [ "$FORCE_NIC_FW_RESET" != "yes" ]; then
+				return
+			fi
+		fi
 	fi
 
 	/sbin/modprobe -a mlx5_core ib_umad
@@ -127,6 +170,11 @@ fw_reset()
 		sleep 1
 	done
 
+	if ! ($CHROOT mlxfwreset -d /dev/mst/mt*_pciconf0 q 2>&1 | grep -w "Driver restart and PCI reset" | grep -qw "\-Supported"); then
+		log "INFO: NIC Firmware reset is not supported. Host power cycle is required"
+		return
+	fi
+
 	log "INFO: Running NIC Firmware reset"
 	save_log
 	if [ "X$mode" == "Xmanufacturing" ]; then
@@ -138,10 +186,15 @@ fw_reset()
 
 	msg=$($CHROOT mlxfwreset -d /dev/mst/mt*_pciconf0 -y -l 3 --sync 1 r 2>&1)
 	if [ $? -ne 0 ]; then
-		log "INFO: NIC Firmware reset failed"
+		log "INFO: NIC Firmware reset failed. Host power cycle is required"
 		log "INFO: $msg"
 	else
 		log "INFO: NIC Firmware reset done"
+		if [ "$(running_nic_fw)" == "${PROVIDED_NIC_FW_VERSION}" ]; then
+			log "INFO: NIC Firmware reset passed. Running NIC FW: ${PROVIDED_NIC_FW_VERSION}"
+		else
+			log "INFO: NIC Firmware reset failed. Host power cycle is required"
+		fi
 	fi
 }
 
@@ -149,11 +202,17 @@ update_nic_firmware()
 {
 	if [ $NIC_FW_UPDATE_DONE -eq 0 ]; then
 		fw_update
+		return $?
 	fi
 }
 
 reset_nic_firmware()
 {
+	if [ "$NIC_FW_RESET" != "yes" ]; then
+		log "Skip NIC Firmware reset"
+		return
+	fi
+
 	if [ $NIC_FW_UPDATE_DONE -eq 1 ]; then
 		if [ $NIC_FW_UPDATE_PASSED -eq 1 ]; then
 			# Reset NIC FW
