bf-bundle-2.7.0-36_24.04_openeuler-20.03sp1
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/openeuler/20.03sp1/create_bfb b/openeuler/20.03sp1/create_bfb
--- a/openeuler/20.03sp1/create_bfb
+++ b/openeuler/20.03sp1/create_bfb
@@ -41,7 +41,7 @@ usage() {
 cat << EOF
 Usage: $(basename $0) [ OPTIONS ]
 OPTIONS:
--k, -kernel,         --kernel <kernel version>  Kernel version for the SmartNIC. Default: $kernel
+-k, -kernel,    --kernel <kernel version>  Kernel version for the SmartNIC. Default: $kernel
 -v, -verbose,   --verbose                       Run script in verbose mode. Will print out each step of execution.
 -h, -help,      --help                          Display help
 
@@ -107,9 +107,20 @@ cd ${WDIR}
 
 initramfs=$WDIR/dump-initramfs-v0
 
+for mod in ${bootctl_module} sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q vitesse
+do
+    if (modinfo -k $kernel $mod 2>/dev/null | grep "filename:" | grep -q builtin); then
+        continue
+    fi
+    if ! (modinfo -k $kernel $mod 2>/dev/null); then
+        continue
+    fi
+    ADD_DRIVERS="$ADD_DRIVERS $mod"
+done
+
 dracut --no-hostonly -m "bash network base systemd systemd-initrd dracut-systemd shutdown udev-rules" \
 	--install "/usr/lib/udev/rules.d/91-tmfifo_net.rules /lib/udev/rules.d/92-oob_net.rules" \
-	--add-drivers "${bootctl_module} sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q" \
+	--add-drivers "${ADD_DRIVERS}" \
 	--filesystems "xfs vfat" --gzip $initramfs ${kernel}
 
 rm -f /etc/udev/rules.d/91-tmfifo_net.rules /etc/udev/rules.d/92-oob_net.rules
@@ -222,7 +233,7 @@ copy_rpm()
 for package in mlxbf-bfscripts util-linux dosfstools e2fsprogs kmod pciutils \
 			   usbutils chkconfig mft mft-oem kernel-mft kmod-kernel-mft-mlnx \
 			   tar xfsprogs coreutils nvme-cli mmc-utils parted which curl \
-			   openssl gawk device-mapper lvm2 iputils sshpass openssh-clients $ADDON_RPMS
+			   openssl gawk device-mapper lvm2 iputils sshpass openssh-clients findutils mokutil $ADDON_RPMS
 do
     copy_rpm $package || true
 done
@@ -250,22 +261,24 @@ mkdir -p mnt
 
 if [ -d ${SDIR}/BF3BMC/ ]; then
 	/bin/rm -rf BF3BMC
-	if (grep -q prod /etc/mlnx-release); then
-		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
-	elif (grep -q dev /etc/mlnx-release); then
-		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	if (grep -q prod /etc/mlnx-release) && [ -d ${SDIR}/BF3BMC/pk ]; then
+		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC
+	elif (grep -q dev /etc/mlnx-release) && [ -d ${SDIR}/BF3BMC/dk ]; then
+		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC
+	elif [ -d ${SDIR}/BF3BMC/qp ]; then
+		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC
 	else
-		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+		echo "WARNING: BF3 BMC Software was not found"
 	fi
-	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC
+	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC || echo "WARNING: BF3 Golden Images for BMC were not found"
 fi
 
 if [ -d ${SDIR}/BF2BMC/ ]; then
 	/bin/rm -rf BF2BMC
 	if (grep -q prod /etc/mlnx-release); then
-		cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+		[ -d ${SDIR}/BF2BMC/pk ] && cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || echo "WARNING: BF2 BMC Software was not found"
 	else
-		cp -a ${SDIR}/BF2BMC/qp/ ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+		[ -d ${SDIR}/BF2BMC/qp ] && cp -a ${SDIR}/BF2BMC/qp ./BF2BMC || echo "WARNING: BF2 BMC Software was not found"
 	fi
 fi
 
@@ -287,7 +300,7 @@ echo "=================================" | tee /dev/kmsg
 echo "Installing OpenEuler Linux. Please wait..." | tee /dev/kmsg
 echo "=================================" | tee /dev/kmsg
 
-modprobe -a sdhci-of-dwcmshc mlxbf_tmfifo mlxbf_gige pinctrl-mlxbf3 8021q dw_mmc_bluefield mmc_block virtio_console nvme ${bootctl_module} 2>&1 | tee /dev/kmsg
+modprobe -a sdhci-of-dwcmshc mlxbf_tmfifo mlxbf_gige pinctrl-mlxbf3 8021q vitesse dw_mmc_bluefield mmc_block virtio_console nvme ${bootctl_module} 2>&1 | tee /dev/kmsg
 modprobe -a mlx5_ib mlxfw ib_umad 2>&1 | tee /dev/kmsg
 
 sleep 5
