bf-bundle-2.8.0-98_24.07-ubuntu-22.04
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/ubuntu/22.04/Dockerfile b/ubuntu/22.04/Dockerfile
--- a/ubuntu/22.04/Dockerfile
+++ b/ubuntu/22.04/Dockerfile
@@ -1,5 +1,7 @@
-#  docker build -t bfb_runtime_ubuntu22.04 -f Dockerfile .
 FROM scratch
+
+ENV DEBIAN_FRONTEND="noninteractive" FLASH_KERNEL_SKIP="yes" RUN_FW_UPDATER="no"
+
 ADD jammy-server-cloudimg-arm64-root.tar.xz /
 ADD qemu-aarch64-static /usr/bin/
 RUN mkdir -p /opt/mellanox/doca/services/
@@ -7,11 +9,6 @@ ADD telemetry-agent /opt/mellanox/doca/services/telemetry
 ADD blueman /opt/mellanox/doca/services/blueman
 ADD infrastructure /opt/mellanox/doca/services/infrastructure
 
-ARG BASE_URL
-ARG DOCA_VERSION
-ARG BSP_VERSION
-ARG DISTRO
-ARG DISTRO_VERSION
 ARG MLNX_FW_UPDATER=mlnx-fw-updater-signed
 WORKDIR /root/workspace
 ADD install.sh .
@@ -21,90 +18,147 @@ ADD build_ubuntu_bfb .
 ADD mlxbf-bootimages.deb .
 ADD BF2BMC ./BF2BMC
 ADD BF3BMC ./BF3BMC
+ADD 10-mlx-console-messages.conf /etc/sysctl.d/
+ADD repos/ /etc/apt/sources.list.d/
+ADD apt-preferences /etc/apt/preferences.d/99doca
+ADD --chown=0:0 --chmod=644 https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.29/deb/Release.key /etc/apt/keyrings/kubernetes.asc
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV FLASH_KERNEL_SKIP=yes
-ENV RUN_FW_UPDATER=no
-
-# Avoid running flash-kernel post install
-RUN mkdir -p /run/systemd; echo docker > /run/systemd/container
-
-RUN add-apt-repository -y ppa:canonical-kernel-bluefield/release
 RUN apt update
-RUN apt upgrade -y
-RUN apt remove --purge -y snapd plymouth
-RUN apt autoremove -y
-RUN apt install -y grub-efi-arm64-signed grub-efi-arm64-bin shim-signed watchdog binutils sbsigntool rasdaemon net-tools nfs-common iptables-persistent rsync tcpdump nvme-cli iputils-arping iputils-ping iputils-tracepath bridge-utils iperf3 bc lm-sensors ifenslave acpid network-manager kexec-tools i2c-tools dc lldpad unzip ipmitool sysstat mmc-utils libhugetlbfs-bin uuid uuid-runtime ntp libgdbm-dev jq libev4 sshpass dracut dracut-network perl-modules wget
-RUN apt install -y docker.io; systemctl disable docker.service || true; systemctl disable docker.socket || true
-RUN apt install -y qemu-user-static qemu-utils qemu-user
-RUN apt install -y python3-pip
-RUN apt install -y build-essential
-RUN apt install -y libpam-pwquality; \
-	sed -i -r -e "s/# minlen =.*/minlen = 12/" /etc/security/pwquality.conf; \
-	sed -i -e '/use_authtok/ipassword\trequired\t\t\tpam_pwhistory.so  remember=3' /etc/pam.d/common-password; \
-	sed -i -r -e "s/# silent/silent/;s/# deny.*/deny = 10/;s/# unlock_time.*/unlock_time = 600/" /etc/security/faillock.conf
-RUN apt install -y python3.10 python3-pyinotify
+RUN dpkg -i /root/workspace/mlxbf-bootimages*.deb
+RUN apt remove -y --purge $(dpkg --list "*openipmi*" | grep openipmi | awk '{print $2}') || true
+RUN apt install -y -f \
+	linux-bluefield-cloud-tools-common=5.15.0-1050.52 \
+	linux-bluefield-headers-5.15.0-1050=5.15.0-1050.52 \
+	linux-bluefield-modules-5.15.0-1050-bluefield=5.15.0-1050.52+1 \
+	linux-bluefield-modules-bluefield=5.15.0-1050.52+1 \
+	linux-bluefield-modules-headers=5.15.0-1050.52+1 \
+	linux-bluefield-modules-source=5.15.0-1050.52+1 \
+	linux-bluefield-modules=5.15.0-1050.52+1 \
+	linux-bluefield-tools-5.15.0-1050=5.15.0-1050.52 \
+	linux-bluefield=5.15.0.1050.52 \
+	linux-buildinfo-5.15.0-1050-bluefield=5.15.0-1050.52 \
+	linux-headers-5.15.0-1050-bluefield=5.15.0-1050.52 \
+	linux-headers-bluefield=5.15.0.1050.52 \
+	linux-image-5.15.0-1050-bluefield=5.15.0-1050.52 \
+	linux-image-bluefield=5.15.0.1050.52 \
+	linux-modules-5.15.0-1050-bluefield=5.15.0-1050.52 \
+	linux-modules-extra-5.15.0-1050-bluefield=5.15.0-1050.52 \
+	linux-tools-5.15.0-1050-bluefield=5.15.0-1050.52 \
+	linux-tools-bluefield=5.15.0.1050.52
 
-# Grub password
-RUN echo 'set superusers="admin"' >> /etc/grub.d/40_custom; \
-	echo 'password_pbkdf2 admin grub.pbkdf2.sha512.10000.5EB1FF92FDD89BDAF3395174282C77430656A6DBEC1F9289D5F5DAD17811AD0E2196D0E49B49EF31C21972669D180713E265BB2D1D4452B2EA9C7413C3471C53.F533423479EE7465785CC2C79B637BDF77004B5CC16C1DDE806BCEA50BF411DE04DFCCE42279E2E1F605459F1ABA3A0928CE9271F2C84E7FE7BF575DC22935B1' >> /etc/grub.d/40_custom; \
-	sed -i -e "s@'gnulinux-simple-\$boot_device_id'@'gnulinux-simple-\$boot_device_id' --unrestricted@" \
-	       -e "s@'gnulinux-\$version-\$type-\$boot_device_id'@'gnulinux-\$version-\$type-\$boot_device_id' --users ''@" /etc/grub.d/10_linux
+RUN apt-get clean -y && \
+    apt-get update -o "Acquire::https::Verify-Peer=false" -y && \
+    apt-get install -o "Acquire::https::Verify-Peer=false" -y ca-certificates locales gzip && \
+    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
+    dpkg-reconfigure locales && \
+    apt-get clean -y && \
+    apt-get update -y && \
+    apt-get autoremove --purge -y \
+        snapd \
+        plymouth \
+    && \
+    apt-get upgrade -y && \
+    apt-get install -y \
+        acpid \
+        bash-completion \
+        bc \
+        bridge-utils \
+        bsdextrautils \
+        build-essential \
+        conntrack \
+        containerd \
+        cri-tools \
+        curl \
+        dc \
+        dmidecode \
+        dnsmasq \
+        docker.io \
+        dosfstools \
+        dracut \
+        dracut-network \
+        ebtables \
+        edac-utils \
+        ethtool \
+        fdisk \
+        file \
+        gawk \
+        grub-efi \
+        i2c-tools \
+        ifenslave \
+        iperf3 \
+        ipmitool \
+        iptables-persistent \
+        iputils-arping \
+        iputils-ping \
+        iputils-tracepath \
+        irqbalance \
+        isc-dhcp-client \
+        jq \
+        kexec-tools \
+        kubeadm \
+        kubelet \
+        kubernetes-cni \
+        less \
+        libev4 \
+        libgdbm-dev \
+        libhugetlbfs-bin \
+        libpam-pwquality \
+        lldpad \
+        lm-sensors \
+        mmc-utils \
+        mstflint \
+        net-tools \
+        network-manager \
+        nfs-common \
+        nftables \
+        ntpsec \
+        nvme-cli \
+        parted \
+        pciutils \
+        pkexec \
+        python3-pip \
+		python3.10 \
+		python3-pyinotify \
+        rasdaemon \
+        rsync \
+        rsyslog \
+        shim-signed \
+        software-properties-common \
+        ssh \
+        sshpass \
+        sudo \
+        sysstat \
+        tcpdump \
+        unzip \
+        usbutils \
+        uuid \
+        uuid-runtime \
+        vim \
+        watchdog \
+        zstd \
+#DOCA Packages
+        doca-runtime \
+        doca-devel \
+        mlnx-snap \
+        strongswan \
+        ${MLNX_FW_UPDATER} \
+    && \
+    rm -rf /var/lib/apt/lists/* /root/workspace/doca-repo.deb /etc/default/grub.d/50-cloudimg-settings.cfg /etc/ssh/sshd_config.d/60-cloudimg-settings.conf /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf && \
+    truncate -s0 /etc/machine-id && \
+    printf 'set superusers="admin"' >> /etc/grub.d/40_custom && \
+    printf 'password_pbkdf2 admin grub.pbkdf2.sha512.10000.5EB1FF92FDD89BDAF3395174282C77430656A6DBEC1F9289D5F5DAD17811AD0E2196D0E49B49EF31C21972669D180713E265BB2D1D4452B2EA9C7413C3471C53.F533423479EE7465785CC2C79B637BDF77004B5CC16C1DDE806BCEA50BF411DE04DFCCE42279E2E1F605459F1ABA3A0928CE9271F2C84E7FE7BF575DC22935B1' >> /etc/grub.d/40_custom && \
+    sed -i -r -e "s/# minlen =.*/minlen = 12/" /etc/security/pwquality.conf && \
+    sed -i -r -e "s/# silent/silent/;s/# deny.*/deny = 10/;s/# unlock_time.*/unlock_time = 600/" /etc/security/faillock.conf && \
+    sed -i -e '/use_authtok/ipassword\trequired\t\t\tpam_pwhistory.so remember=3' /etc/pam.d/common-password && \
+    sed -i -e "s@'gnulinux-simple-\$boot_device_id'@'gnulinux-simple-\$boot_device_id' --unrestricted@" -e "s@'gnulinux-\$version-\$type-\$boot_device_id'@'gnulinux-\$version-\$type-\$boot_device_id' --users ''@" /etc/grub.d/10_linux && \
+    sed -i -e "s/FORCE_MODE=.*/FORCE_MODE=yes/" /etc/infiniband/openib.conf && \
+    sed -i -r -e "s/^(MACAddressPolicy.*)/# \1/" /usr/lib/systemd/network/99-default.link && \
+    update-pciids && \
+    wget -qO - https://linux.mellanox.com/public/repo/doca/latest/ubuntu22.04/aarch64/GPG-KEY-Mellanox.pub | apt-key add -
 
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
 
-RUN mkdir -p -m 755 /etc/apt/keyrings/
-RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
-RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
-
-RUN wget -qO - $BASE_URL/doca/GPG-KEY-Mellanox.pub | sudo apt-key add -
-
-RUN apt update
-# Install Libvirt+QEMU+KVM
-RUN apt install -y bridge-utils cpu-checker libvirt-clients libvirt-daemon qemu qemu-kvm
-RUN apt upgrade -y
-RUN apt install -y containerd runc
-RUN apt install -y kubelet=1.29.3-1.1 kubernetes-cni=1.3.0-1.1 cri-tools=1.29.0-1.1 kubeadm=1.29.3-1.1
-RUN rm -f /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
-RUN apt-mark hold kubelet cri-tools kubernetes-cni kubeadm
-RUN echo "deb [trusted=yes] ${BASE_URL}/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/arm64-dpu/ /" | sudo tee /etc/apt/sources.list.d/doca.base.list
-RUN apt update
-RUN apt install -y mstflint=4.26.0-1
-RUN apt-mark hold mstflint
-RUN dpkg -i /root/workspace/mlxbf-bootimages*.deb
-RUN apt remove -y --purge $(dpkg --list "*openipmi*" | grep openipmi | awk '{print $2}') || true
-RUN apt install -y -f $MLNX_FW_UPDATER
-
-RUN apt install -y -f \
-	linux-bluefield=5.15.0.1042.44 \
-	linux-bluefield-cloud-tools-common=5.15.0-1042.44 \
-	linux-bluefield-headers-5.15.0-1042=5.15.0-1042.44 \
-	linux-bluefield-modules=5.15.0-1042.44+1 \
-	linux-bluefield-modules-5.15.0-1042-bluefield=5.15.0-1042.44+1 \
-	linux-bluefield-modules-bluefield=5.15.0-1042.44+1 \
-	linux-bluefield-modules-headers=5.15.0-1042.44+1 \
-	linux-bluefield-modules-source=5.15.0-1042.44+1 \
-	linux-bluefield-tools-5.15.0-1042=5.15.0-1042.44 \
-	linux-buildinfo-5.15.0-1042-bluefield=5.15.0-1042.44 \
-	linux-headers-5.15.0-1042-bluefield=5.15.0-1042.44 \
-	linux-headers-bluefield=5.15.0.1042.44 \
-	linux-image-5.15.0-1042-bluefield=5.15.0-1042.44 \
-	linux-image-bluefield=5.15.0.1042.44 \
-	linux-modules-5.15.0-1042-bluefield=5.15.0-1042.44 \
-	linux-modules-extra-5.15.0-1042-bluefield=5.15.0-1042.44 \
-	linux-tools-5.15.0-1042-bluefield=5.15.0-1042.44 \
-	linux-tools-bluefield=5.15.0.1042.44
-
-RUN apt install -y -f doca-runtime doca-devel mlx-openipmi || true
-RUN apt --fix-broken install -y || true
-RUN apt install -y mlnx-libsnap mlnx-snap
-RUN apt update || true
-RUN /usr/sbin/dpkg-reconfigure bf-release || true
-RUN mkdir -p /etc/kubelet.d
-RUN sed -i -r -e "s/^(MACAddressPolicy.*)/# \1/" /usr/lib/systemd/network/99-default.link
-
 # Manage system services
-RUN systemctl disable mlx-regex.service || true
 RUN systemctl enable NetworkManager.service || true
 RUN systemctl enable NetworkManager-wait-online.service || true
 RUN systemctl enable networking.service || true
@@ -113,6 +167,8 @@ RUN systemctl enable acpid.service || true
 RUN systemctl enable mlx-openipmi.service || true
 RUN systemctl enable mlx_ipmid.service || true
 RUN systemctl enable set_emu_param.service || true
+RUN systemctl enable mst || true
+RUN systemctl disable mlx-regex.service || true
 RUN systemctl disable openvswitch-ipsec || true
 RUN systemctl disable srp_daemon.service || true
 RUN systemctl disable ibacm.service || true
@@ -125,12 +181,6 @@ RUN systemctl disable kubelet.service || true
 RUN systemctl disable containerd.service || true
 RUN systemctl disable ModemManager.service || true
 
-RUN /usr/sbin/update-pciids || true
-
-RUN /bin/rm -f /var/lib/dbus/machine-id /etc/machine-id; touch /var/lib/dbus/machine-id /etc/machine-id
-
-RUN /bin/rm -f /etc/ssh/sshd_config.d/60-cloudimg-settings.conf || true
-RUN /bin/rm -f /etc/default/grub.d/50-cloudimg-settings.cfg || true
 
 # openibd to support MLNX_OFED drivers coming with Canonical's deb
 RUN sed -i -e "s/FORCE_MODE=.*/FORCE_MODE=yes/" /etc/infiniband/openib.conf
@@ -153,4 +203,4 @@ RUN mkdir -p /boot/efi/EFI/ubuntu/; \
 	   /usr/lib/shim/fbaa64.efi \
 	/boot/efi/EFI/BOOT/
 
-RUN sed -i -e "s/signed/@IMAGE_TYPE@@CUSTOM_VERSION@/" -e "s/prod/@IMAGE_TYPE@@CUSTOM_VERSION@/" /etc/mlnx-release
+RUN sed -i "s/_unsigned|_prod|_dev//" /etc/mlnx-release; sed -i "s/$/_@IMAGE_TYPE@@CUSTOM_VERSION@/" /etc/mlnx-release
diff --git a/ubuntu/22.04/create_bfb b/ubuntu/22.04/create_bfb
--- a/ubuntu/22.04/create_bfb
+++ b/ubuntu/22.04/create_bfb
@@ -1,87 +1,34 @@
 #!/bin/bash
 
-# Copyright (c) 2020, Mellanox Technologies
-# All rights reserved.
+###############################################################################
 #
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
+# Copyright 2023 NVIDIA Corporation
 #
-# 1. Redistributions of source code must retain the above copyright notice, this
-#    list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright notice,
-#    this list of conditions and the following disclaimer in the documentation
-#    and/or other materials provided with the distribution.
+# Permission is hereby granted, free of charge, to any person obtaining a copy of
+# this software and associated documentation files (the "Software"), to deal in
+# the Software without restriction, including without limitation the rights to
+# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
+# the Software, and to permit persons to whom the Software is furnished to do so,
+# subject to the following conditions:
 #
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
-# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
-# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
 #
-# The views and conclusions contained in the software and documentation are those
-# of the authors and should not be interpreted as representing official policies,
-# either expressed or implied, of the FreeBSD Project.
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
+# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
+# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
+# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
+# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+#
+###############################################################################
 
 set -e
 
 SDIR="/root/workspace"
 BFB="${BFB:-/lib/firmware/mellanox/boot/default.bfb}"
 CAPSULE="${CAPSULE:-/lib/firmware/mellanox/boot/capsule/boot_update2.cap}"
-verbose=0
-kdir=$(/bin/ls -1d /lib/modules/4.20* /lib/modules/5.* 2> /dev/null | head -1)
-if [ -n "$kdir" ]; then
-	kernel=${kdir##*/}
-else
-	kernel=$(/bin/ls -1 /lib/modules/ | head -1)
-fi
-
-usage() {
-cat << EOF
-Usage: $(basename $0) [ OPTIONS ]
-OPTIONS:
--i, -install_bfb,    --install_bfb <BFB>        Installation BFB to be used as a basis for the target BFB. Default: $BFB
--k, -kernel,         --kernel <kernel version>  Kernel version for the SmartNIC. Default: $kernel
--v, -verbose,   --verbose                       Run script in verbose mode. Will print out each step of execution.
--h, -help,      --help                          Display help
-
-EOF
-}
-
-
-options=$(getopt -l "install_bfb:,kernel:,help,verbose" -o "i:k:hv" -a -- "$@")
-
-eval set -- "$options"
-
-while true
-do
-	case $1 in
-		-h|--help)
-			usage
-			exit 0
-			;;
-		-i|--install_bfb)
-			shift
-			BFB=$1
-			;;
-		-k|--kernel)
-			shift
-			kernel=$1
-			;;
-		-v|--verbose)
-			verbose=1
-			set -xv
-			;;
-		--)
-			shift
-			break;;
-	esac
-	shift
-done
+kernel=$(/bin/ls -1 /lib/modules/ | head -1)
 
 SCRIPTS_DIR=$(dirname $0)
 
@@ -130,7 +77,15 @@ initramfs=$(realpath $initramfs)
 initramfs=$WDIR/dump-initramfs-v0
 
 ADD_DRIVERS=""
-for mod in mlxbf-bootctl sdhci-of-dwcmshc mlxbf-tmfifo dw_mmc-bluefield mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q
+for mod in mlxbf-bootctl dw_mmc dw_mmc-pltfm mmc_block dw_mmc-bluefield \
+	sdhci sdhci-of-dwcmshc mlxbf-tmfifo \
+	mlx5_core mlx5_ib mlxfw ib_umad nvme \
+	nvme-rdma nvme-tcp ib_ipoib ib_iser \
+	mst_pci mst_pciconf bf3_livefish \
+	gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige \
+	pinctrl-mlxbf3 8021q \
+	ipmi_devintf ipmb_host ipmi_ssif i2c-mlxbf \
+	nls_iso8859-1 $ADDON_KERNEL_MODULES
 do
 	if (modinfo -k $kernel $mod 2>/dev/null | grep "filename:" | grep -q builtin); then
 		continue
@@ -197,37 +152,6 @@ copy_file()
 	done
 }
 
-module_exist()
-{
-	mod=$(find ./lib/modules/$kernel -name "${1}.ko*" 2> /dev/null)
-	test -n "$mod"
-	return $?
-}
-
-copy_module()
-{
-	if module_exist $1; then
-		return
-	fi
-
-	if (modinfo -k $kernel $1 2>/dev/null | grep "filename:" | grep -q builtin); then
-		return
-	fi
-
-	if ! (modinfo -k $kernel $1 2>/dev/null); then
-		return
-	fi
-
-	for mod in $(modinfo -F depends -k $kernel $1 | tr -s ',' ' ')
-	do
-		copy_module $mod
-	done
-
-	mod_ko=$(modinfo -F filename -k $kernel $1)
-	mkdir -p ./$(dirname ${mod_ko})
-	sudo cp ${mod_ko} ./${mod_ko}
-}
-
 (cd usr/bin; sudo ln -s xz xzcat)
 cp $(readlink -f /usr/bin/which) ./usr/bin/which
 
@@ -250,12 +174,15 @@ libpython3_minimal=$(dpkg -S /usr/lib/python3*/os.py | head -1 | cut -d ':' -f 1
 libpython3=$(dpkg -S /usr/lib/aarch64-linux-gnu/libpython3.*.so.1 | head -1 | cut -d ':' -f 1 | tr -d ',')
 python3_distutils=$(dpkg -S /usr/lib/python3.*/distutils | head -1 | cut -d ':' -f 1 | tr -d ',')
 python3_lib2to3=$(dpkg -S /usr/lib/python3.*/lib2to3 | head -1 | cut -d ':' -f 1 | tr -d ',')
+python_bin=$(readlink -f /usr/bin/python)
+python_deb=$(dpkg -S $python_bin | head -1 | cut -d ':' -f 1 | tr -d ',')
+python_ver=$(python -V | cut -d ' ' -f 2 | cut -d '.' -f1,2)
 
 for deb in mlxbf-scripts mft mft-oem dosfstools e2fsprogs fdisk kmod pciutils \
 		   usbutils tar coreutils nvme-cli mmc-utils iputils-ping uuid-runtime \
 		   sshpass openssh-client util-linux ipmitool procps debianutils \
 		   iproute2 findutils perl-base $libperl $perl_modules \
-		   $libpython3_minimal $python3_distutils $python3_lib2to3 $python3 \
+		   $libpython3_minimal $python3_distutils $python3_lib2to3 $python3 $python_deb \
 		   $libpython3 bsdutils libexpat1 wget net-tools isc-dhcp-client $ADDON_DEBS
 do
 	for pfile in $(dpkg -L $deb)
@@ -282,17 +209,14 @@ do
 	done
 done
 
-for mod in mlxbf_tmfifo dw_mmc-bluefield dw_mmc dw_mmc-pltfm mmc_block sdhci sdhci-of-dwcmshc nvme-rdma nvme-tcp nvme mlx5_ib mlxfw ib_umad ib_ipoib ib_iser mst_pci mst_pciconf bf3_livefish ipmi_devintf ipmb_host ipmi_ssif i2c-mlxbf nls_iso8859-1 $ADDON_KERNEL_MODULES
-do
-	copy_module $mod
-done
-sudo depmod -a -b ./ $kernel
-
 sudo mkdir -p usr/share/misc/ bin/ var/log/watchdog
 sudo cp /usr/share/misc/pci.ids usr/share/misc/
 sudo cp /etc/watchdog.conf etc
 if ! [ -e usr/bin/python ]; then
-	ln -s python3.10 usr/bin/python
+	ln -s python${python_ver} usr/bin/python
+fi
+if ! [ -e usr/bin/python3 ]; then
+	ln -s python${python_ver} usr/bin/python3
 fi
 
 # Make sure we can load mlx-bootctl
@@ -323,28 +247,38 @@ sudo mkdir -p mnt
 
 if [ -d ${SDIR}/BF3BMC/ ]; then
 	/bin/rm -rf BF3BMC
-	if (grep -q prod /etc/mlnx-release) && [ -d ${SDIR}/BF3BMC/pk ]; then
-		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC
-	elif (grep -q dev /etc/mlnx-release) && [ -d ${SDIR}/BF3BMC/dk ]; then
-		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC
-	elif [ -d ${SDIR}/BF3BMC/qp ]; then
-		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC
+	if (grep -q prod /etc/mlnx-release); then
+		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	elif (grep -q dev /etc/mlnx-release); then
+		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
 	else
-		echo "WARNING: BF3 BMC Software was not found"
+		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
 	fi
-	if [ ! -d ./BF3BMC/golden_images ]; then
-		[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC || echo "WARNING: BF3 Golden Images for BMC were not found"
-	fi
+	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC
 fi
 
 if [ -d ${SDIR}/BF2BMC/ ]; then
 	/bin/rm -rf BF2BMC
 	if (grep -q prod /etc/mlnx-release); then
-		[ -d ${SDIR}/BF2BMC/pk ] && cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || echo "WARNING: BF2 BMC Software was not found"
+		cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
 	else
-		[ -d ${SDIR}/BF2BMC/qp ] && cp -a ${SDIR}/BF2BMC/qp ./BF2BMC || echo "WARNING: BF2 BMC Software was not found"
+		cp -a ${SDIR}/BF2BMC/qp/ ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
 	fi
 fi
+
+# Remove hostname that includes docker container's id
+/bin/rm -f ./etc/hostname
+echo localhost > /etc/hostname
+
+touch ./etc/fstab
+
+# Prevent the modules from loading automatically by blacklisting them
+cat > ./etc/modprobe.d/blacklist-mlx5.conf << EOF
+blacklist mlx5_core
+blacklist mlx5_ib
+blacklist mlxfw
+blacklist ib_umad
+EOF
 
 ex mkdir -p ubuntu
 # Tar the image
@@ -368,8 +302,6 @@ modprobe mlxbf_tmfifo > /dev/null 2>&1
 modprobe -a ipmi_msghandler ipmi_devintf i2c-mlxbf
 modprobe ipmb_host slave_add=0x10
 echo ipmb-host 0x1011 > /sys/bus/i2c/devices/i2c-1/new_device
-modprobe -a mlx5_ib mlxfw ib_umad
-modprobe nvme > /dev/null 2>&1
 insmod /mlx-bootctl.ko > /dev/null 2>&1
 insmod /sbsa_gwdt.ko > /dev/null 2>&1
 /usr/sbin/watchdog > /dev/null 2>&1
@@ -384,6 +316,7 @@ if [ \$? -eq 0 ]; then
 	printf_msg "Installation finished. Rebooting..."
 	printf_msg "==================================="
 	printf_msg
+	sleep 3
 	reboot -f
 else
 	printf_msg "========================"
