BCLinux 7.6: Updated to DOCA_1.5.1_BSP_3.9.3
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/bclinux/7.6/create_bfb b/bclinux/7.6/create_bfb
--- a/bclinux/7.6/create_bfb
+++ b/bclinux/7.6/create_bfb
@@ -32,8 +32,8 @@ set -e
 LANG=C
 BF_HOSTNAME="localhost"
 SDIR="/root/workspace"
-#BFB="${BFB:-/lib/firmware/mellanox/boot/default.bfb}"
-BFB="${BFB:-/root/workspace/install.bfb}"
+BFB="${BFB:-/lib/firmware/mellanox/boot/default.bfb}"
+# BFB="${BFB:-/root/workspace/install.bfb}"
 CAPSULE="${CAPSULE:-/lib/firmware/mellanox/boot/capsule/boot_update2.cap}"
 verbose=0
 kdir=$(/bin/ls -1d /lib/modules/4.19* /lib/modules/4.20* /lib/modules/5.* 2> /dev/null | head -1)
@@ -87,6 +87,9 @@ do
         shift
 done
 
+bootctl_module="mlxbf-bootctl"
+
+modinfo -n -k $kernel "mlx-bootctl" 2> /dev/null && bootctl_module="mlx-bootctl"
 
 SCRIPTS_DIR=`dirname $0`
 
@@ -130,11 +133,7 @@ ex cd ${WDIR}
 ex /bin/rm -rf initramfs
 
 initramfs=$WDIR/dump-initramfs-v0
-ex $mkbfb -x ${BFB}
-
-initramfs="dump-initramfs-v0"
-
-mkinitrd --force --with=xfs --with=dw_mmc-bluefield --with=dw_mmc-pltfm --with=dw_mmc --with=mtd_blkdevs --with=mmc_block --with=mlxbf_gige --with=mlxbf-tmfifo --with=mlx5_ib /boot/initramfs-${kernel}.img $kernel
+ex dracut --no-hostonly -m "bash network base shutdown" --force-drivers "${bootctl_module} mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib ib_umad nvme nvme-rdma nvme-fc nvme-fabrics nvme-core" --filesystems "xfs vfat" --gzip $initramfs ${kernel}
 
 cat > /etc/default/grub << EOF
 GRUB_TIMEOUT=0
@@ -143,26 +142,130 @@ GRUB_DEFAULT=saved
 GRUB_DISABLE_SUBMENU=true
 GRUB_TERMINAL=console
 GRUB_SERIAL_COMMAND="serial --unit=1"
-GRUB_CMDLINE_LINUX="crashkernel=auto  console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 modprobe.blacklist=mlx5_core,mlx5_ib"
+GRUB_CMDLINE_LINUX="crashkernel=auto console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 modprobe.blacklist=mlx5_core,mlx5_ib net.ifnames=0 biosdevname=0"
 GRUB_DISABLE_RECOVERY="true"
 GRUB_TIMEOUT_STYLE=countdown
 GRUB_DISABLE_OS_PROBER=false
 EOF
 
-initramfs_type=`file $initramfs`
-case "${initramfs_type}" in
-        *LZMA*)
-                echo "Uncompressing initramfs: $initramfs_type"
-                mv ${initramfs} ${initramfs}.xz
-                xz -d ${initramfs}.xz
-                ;;
+
+case "$(file --brief --mime-type "$initramfs")" in
+	"application/x-lzma")
+		cat_initrd="lzcat" ;;
+	"application/x-lz4")
+		cat_initrd="lz4cat" ;;
+	*)
+		cat_initrd="zcat" ;;
 esac
 
 echo "Rebuilding $initramfs"
 
 mkdir -p ${WDIR}/initramfs
 cd initramfs
-cpio -id < ../$initramfs
+$cat_initrd "$initramfs" | sudo cpio -i
+
+copy_bin()
+{
+	if [ -e $1 ]; then
+		bin=$1
+	else
+		bin=`which $1 2> /dev/null`
+	fi
+	if [ -z "$bin" ]; then
+		echo "ERROR: Cannot find $1"
+		return 1
+	fi
+	sudo mkdir -p .`dirname $bin`
+	if [ -e .${bin} ]; then
+		/bin/rm -f .${bin}
+	fi
+	sudo cp -a $bin .${bin}
+
+	# Copy dependencies
+	for lib in `ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}' | grep -v '(0x0'`
+	do
+		if [ -e .$lib ]; then
+			continue
+		fi
+		sudo mkdir -p .`dirname $lib`
+		sudo cp -a $lib .$lib
+		if [ -h $lib ]; then
+			tlib=`readlink -f $lib`
+			if [ ! -e .$tlib ]; then
+				sudo mkdir -p .`dirname $tlib`
+				sudo cp $tlib .$tlib
+			fi
+		fi
+	done
+}
+
+copy_rpm()
+{
+	package=$1
+
+	if ! (rpm -q $package); then
+		yum install -y $package
+	fi
+
+	case $package in
+		chkconfig)
+			for f in `rpm -ql $package | grep -v share`
+			do
+				if [ -d $f ]; then
+					mkdir -p .${f}
+				else
+					copy_bin $f
+				fi
+			done
+			;;
+		*mft*)
+			for f in `rpm -ql $package | grep -v man`
+			do
+				if [ -d $f ]; then
+					continue
+				fi
+				copy_bin $f
+			done
+			;;
+		*)
+			for f in `rpm -ql $package | grep -vE 'share|build-id'`
+			do
+				if [ -d $f ]; then
+					continue
+				fi
+				copy_bin $f
+			done
+			;;
+	esac
+}
+
+kernel_mft_rpm=`rpm -qa --queryformat "[%{NAME}]" "*kernel-mft*" | tr -s '\n' ' '`
+# Copy the content of RPM packages
+for package in mlxbf-bfscripts util-linux dosfstools e2fsprogs kmod pciutils usbutils chkconfig mft mft-oem $kernel_mft_rpm tar xfsprogs coreutils parted which curl $ADDON_RPMS
+do
+	copy_rpm $package || true
+done
+
+# Copy tools
+for tool in	xz efibootmgr bash getopt hexdump mstflint lspci perl \
+		lsblk shutdown systemctl strings \
+		mlxbf-bootctl id grep $ADDON_TOOLS
+do
+	if [ -d $tool ]; then
+		continue
+	fi
+	copy_bin $tool
+done
+
+sudo depmod -a -b ./ $kernel
+sudo ldconfig -r ./
+sudo mkdir -p usr/share/hwdata/ bin/
+sudo cp /usr/share/hwdata/pci.ids ./usr/share/hwdata/
+sudo mkdir -p ./lib/firmware/mellanox/boot/
+sudo cp /lib/firmware/mellanox/boot/default.bfb ./lib/firmware/mellanox/boot/default.bfb
+sudo cp -a /lib/firmware/mellanox/boot/capsule ./lib/firmware/mellanox/boot/
+sudo cp $CAPSULE ./lib/firmware/mellanox/boot/capsule/
+sudo mkdir -p mnt
 
 # CVE-2021-4034 workaround
 chmod 0755 /usr/bin/pkexec
@@ -172,13 +275,17 @@ ex mkdir -p bclinux
 XZ_OPT="--threads=0 -9 --verbose" tar -cJp --exclude='./Repo' --exclude='./workspace'  --exclude='./root/workspace' --exclude='./root/*' --exclude='./tmp/*' --exclude='./run/*' --exclude='./sys/*' --exclude='./proc/*' --exclude='./dev/*' --exclude='./.dockerenv' --exclude='./root/rpmbuild' --exclude='./root/.rpmmacros' --exclude='./root/.bash_history' --exclude='./var/tmp/*rpm' --exclude='./bin/qemu-aarch64-static' --exclude='./usr/bin/qemu-aarch64-static' --exclude='./usr/bin/qemu-arm-static' --exclude='./var/lib/yum/*' --exclude='./var/cache/yum/*' -f ./bclinux/image.tar.xz -C / .
 ex install -m 0755 ${SDIR}/install.sh ./bclinux/install.sh
 
-cat > etc/init.d/install-bclinux << EOF
+mkdir scripts
+cat > scripts/install-bclinux.sh << EOF
 #!/bin/sh
 
 echo
 echo "==================================" | tee /dev/kmsg
 echo "Installing BCLinux. Please wait..." | tee /dev/kmsg
 echo "==================================" | tee /dev/kmsg
+
+modprobe -a mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console ${bootctl_module} 2>&1 | tee /dev/kmsg
+modprobe -a mlx5_ib ib_uverbs 2>&1 | tee /dev/kmsg
 
 sleep 5
 
@@ -188,7 +295,7 @@ if [ \$? -eq 0 ]; then
         echo "Installation finished. Rebooting..." | tee /dev/kmsg
         echo "===================================" | tee /dev/kmsg
         echo
-	sleep 3
+        sleep 3
         reboot -f
 else
         echo "=========================" | tee /dev/kmsg
@@ -196,11 +303,10 @@ else
         echo "=========================" | tee /dev/kmsg
 fi
 EOF
-ex chmod 755 etc/init.d/install-bclinux
-ln -snf ../init.d/install-bclinux etc/rcS.d/S99install-bclinux
+sed -i -e "s@source_conf /etc/conf.d@&\nbash -x /scripts/install-bclinux.sh@" init
 
 # Make initramfs with new bclinux
-find . | cpio -H newc -o | gzip -9 > ../$initramfs
+find . | cpio -H newc -o | gzip -9 > $initramfs
 
 # Make bfb
 cd ..
@@ -210,10 +316,13 @@ if [ ! -e $CAPSULE ]; then
 fi
 
 boot_args=$(mktemp)
+boot_args2=$(mktemp)
 boot_path=$(mktemp)
 boot_desc=$(mktemp)
 printf "console=ttyAMA1 console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 earlycon=pl011,0x01800000 initrd=initramfs quiet" > \
 	"$boot_args"
+printf "console=ttyAMA1 console=hvc0 console=ttyAMA0 earlycon=pl011,0x13010000 initrd=initramfs quiet" > \
+	"$boot_args2"
 
 printf "VenHw(F019E406-8C9C-11E5-8797-001ACA00BFC4)/Image" > "$boot_path"
 printf "Linux from rshim" > "$boot_desc"
@@ -227,9 +336,10 @@ fi
 mkdir -p /workspace
 
 ex $mkbfb \
-	--initramfs "$initramfs" \
+	--image "$vmlinuz" --initramfs "$initramfs" \
 	--capsule "$CAPSULE" \
-	--boot-args "$boot_args" \
+	--boot-args-v0 "$boot_args" \
+	--boot-args-v2 "$boot_args2" \
 	--boot-path "$boot_path" \
 	--boot-desc "$boot_desc" \
 	${BFB} /workspace/${BCLINUX_BFB}
