RockyLinux 8.6 DOCA_2.6.0_BSP_4.6.0
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/rockylinux/8.6/create_bfb b/rockylinux/8.6/create_bfb
--- a/rockylinux/8.6/create_bfb
+++ b/rockylinux/8.6/create_bfb
@@ -1,36 +1,31 @@
 #!/bin/bash
 
-# Copyright (c) 2020, Mellanox Technologies
-# All rights reserved.
+###############################################################################
 #
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
+# Copyright 2023 NVIDIA Corporation
 #
-# 1. Redistributions of source code must retain the above copyright notice, this
-#    list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright notice,
-#    this list of conditions and the following disclaimer in the documentation
-#    and/or other materials provided with the distribution.
+# Permission is hereby granted, free of charge, to any person obtaining a copy of
+# this software and associated documentation files (the "Software"), to deal in
+# the Software without restriction, including without limitation the rights to
+# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
+# the Software, and to permit persons to whom the Software is furnished to do so,
+# subject to the following conditions:
 #
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
-# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
-# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
 #
-# The views and conclusions contained in the software and documentation are those
-# of the authors and should not be interpreted as representing official policies,
-# either expressed or implied, of the FreeBSD Project.
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
+# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
+# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
+# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
+# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+#
+###############################################################################
 
 set -e
 
 LANG=C
-BF_HOSTNAME="localhost"
 SDIR="/root/workspace"
 BFB="${BFB:-/lib/firmware/mellanox/boot/default.bfb}"
 CAPSULE="${CAPSULE:-/lib/firmware/mellanox/boot/capsule/boot_update2.cap}"
@@ -44,9 +39,8 @@ fi
 
 usage() {
 cat << EOF
-Usage: `basename $0` [ OPTIONS ]
+Usage: $(basename $0) [ OPTIONS ]
 OPTIONS:
--H, -hostname,       --hostname <hostname>      Hostname for the SmartNIC. Default: $BF_HOSTNAME
 -k, -kernel,         --kernel <kernel version>  Kernel version for the SmartNIC. Default: $kernel
 -v, -verbose,   --verbose                       Run script in verbose mode. Will print out each step of execution.
 -h, -help,      --help                          Display help
@@ -55,8 +49,7 @@ OPTIONS:
 EOF
 }
 
-
-options=$(getopt -l "hostname:,kernel:,help,verbose" -o "H:k:hv" -a -- "$@")
+options=$(getopt -l "kernel:,help,verbose" -o "k:hv" -a -- "$@")
 
 eval set -- "$options"
 
@@ -66,10 +59,6 @@ do
                 -h|--help)
                     usage
                     exit 0
-                    ;;
-                -H|--hostname)
-                    shift
-                    BF_HOSTNAME=$1
                     ;;
                 -k|--kernel)
                     shift
@@ -90,7 +79,7 @@ bootctl_module="mlxbf-bootctl"
 
 modinfo -n -k $kernel "mlx-bootctl" > /dev/null 2>&1 && bootctl_module="mlx-bootctl"
 
-SCRIPTS_DIR=`dirname $0`
+SCRIPTS_DIR=$(dirname $0)
 
 WDIR=${WDIR:-/root/workspace/bfb}
 
@@ -99,21 +88,17 @@ echo "Work directory: $WDIR"
 BFB_FILENAME="$(cat /etc/mlnx-release).bfb"
 
 PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/mellanox/scripts:/opt/mellanox/scripts/bin
-mkbfb=`which mlx-mkbfb`
+mkbfb=$(which mlx-mkbfb)
 
 if [ ! -x "${mkbfb}" ]; then
-    echo "- ERROR: mlx-mkbfb is required to build BFB image"
-    exit 1
+	echo "- ERROR: mlx-mkbfb is required to build BFB image"
+	exit 1
 fi
 
 if [[ ! -n "${BFB}" || ! -e "${BFB}" ]]; then
-    echo "- ERROR: BFB was not found"
-    exit 1
+	echo "- ERROR: BFB was not found"
+	exit 1
 fi
-
-echo ${BF_HOSTNAME} > /etc/hostname
-
-hostname ${BF_HOSTNAME}
 
 /bin/rm -rf ${WDIR}
 mkdir -p ${WDIR}
@@ -124,7 +109,7 @@ initramfs=$WDIR/dump-initramfs-v0
 
 dracut --no-hostonly -m "bash network base systemd systemd-initrd dracut-systemd shutdown udev-rules" \
 	--install "/usr/lib/udev/rules.d/91-tmfifo_net.rules /lib/udev/rules.d/92-oob_net.rules" \
-	--add-drivers "${bootctl_module} sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib mlxfw ib_umad nvme" \
+	--add-drivers "${bootctl_module} sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf2 gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q" \
 	--filesystems "xfs vfat" --gzip $initramfs ${kernel}
 
 rm -f /etc/udev/rules.d/91-tmfifo_net.rules /etc/udev/rules.d/92-oob_net.rules
@@ -163,30 +148,30 @@ copy_bin()
     if [ -e $1 ]; then
         bin=$1
     else
-        bin=`which $1 2> /dev/null`
+        bin=$(which $1 2> /dev/null)
     fi
     if [ -z "$bin" ]; then
         echo "ERROR: Cannot find $1"
         return 1
     fi
-    mkdir -p .`dirname $bin`
+    mkdir -p .$(dirname $bin)
     if [ -e .${bin} ]; then
         /bin/rm -f .${bin}
     fi
     cp -a $bin .${bin}
 
     # Copy dependencies
-    for lib in `ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}' | grep -v '(0x0'`
+    for lib in $(ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}' | grep -v '(0x0')
     do
         if [ -e .$lib ]; then
             continue
         fi
-        mkdir -p .`dirname $lib`
+        mkdir -p .$(dirname $lib)
         cp -a $lib .$lib
         if [ -h $lib ]; then
-            tlib=`readlink -f $lib`
+            tlib=$(readlink -f $lib)
             if [ ! -e .$tlib ]; then
-                mkdir -p .`dirname $tlib`
+                mkdir -p .$(dirname $tlib)
                 cp $tlib .$tlib
             fi
         fi
@@ -203,7 +188,7 @@ copy_rpm()
 
     case $package in
         chkconfig)
-            for f in `rpm -ql $package | grep -v share`
+            for f in $(rpm -ql $package | grep -v share)
             do
                 if [ -d $f ]; then
                     mkdir -p .${f}
@@ -213,7 +198,7 @@ copy_rpm()
             done
             ;;
         *mft*)
-            for f in `rpm -ql $package | grep -v man`
+            for f in $(rpm -ql $package | grep -v man)
             do
                 if [ -d $f ]; then
                     continue
@@ -222,7 +207,7 @@ copy_rpm()
             done
             ;;
         *)
-            for f in `rpm -ql $package | grep -vE 'share|build-id'`
+            for f in $(rpm -ql $package | grep -vE 'share|build-id')
             do
                 if [ -d $f ]; then
                     continue
@@ -234,7 +219,7 @@ copy_rpm()
 }
 
 # Copy the content of RPM packages
-for package in mlxbf-bfscripts util-linux dosfstools e2fsprogs kmod pciutils usbutils chkconfig mft mft-oem kernel-mft kmod-kernel-mft-mlnx tar xfsprogs coreutils-single nvme-cli mmc-utils parted which curl openssl gawk lvm2-libs device-mapper lvm2 $ADDON_RPMS
+for package in mlxbf-bfscripts util-linux dosfstools e2fsprogs kmod pciutils usbutils chkconfig mft mft-oem kernel-mft kmod-kernel-mft-mlnx tar xfsprogs coreutils-single nvme-cli mmc-utils parted which curl openssl gawk lvm2-libs device-mapper lvm2 iputils sshpass openssh-clients $ADDON_RPMS
 do
     copy_rpm $package || true
 done
@@ -242,7 +227,7 @@ done
 # Copy tools
 for tool in xz efibootmgr bash getopt hexdump mstflint lspci perl \
         lsblk shutdown systemctl strings \
-        mlxbf-bootctl id grep $ADDON_TOOLS
+        mlxbf-bootctl id grep jq $ADDON_TOOLS
 do
     if [ -d $tool ]; then
         continue
@@ -260,6 +245,27 @@ cp -a /lib/firmware/mellanox/boot/capsule ./lib/firmware/mellanox/boot/
 cp $CAPSULE ./lib/firmware/mellanox/boot/capsule/
 mkdir -p mnt
 
+if [ -d ${SDIR}/BF3BMC/ ]; then
+	/bin/rm -rf BF3BMC
+	if (grep -q prod /etc/mlnx-release); then
+		cp -a ${SDIR}/BF3BMC/pk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	elif (grep -q dev /etc/mlnx-release); then
+		cp -a ${SDIR}/BF3BMC/dk ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	else
+		cp -a ${SDIR}/BF3BMC/qp ./BF3BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	fi
+	[ -d ${SDIR}/BF3BMC/golden_images ] && cp -a ${SDIR}/BF3BMC/golden_images ./BF3BMC
+fi
+
+if [ -d ${SDIR}/BF2BMC/ ]; then
+	/bin/rm -rf BF2BMC
+	if (grep -q prod /etc/mlnx-release); then
+		cp -a ${SDIR}/BF2BMC/pk ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	else
+		cp -a ${SDIR}/BF2BMC/qp/ ./BF2BMC || ( echo "ERROR: BMC Software was not found" && exit 1 )
+	fi
+fi
+
 mkdir -p rocky
 # Tar the image
 XZ_OPT="--threads=0 -9 --verbose" tar -cJp --exclude='./workspace' --exclude='./signing-local' --exclude='./signing-shared' --exclude='./var/run/docker.sock' \
@@ -267,6 +273,7 @@ XZ_OPT="--threads=0 -9 --verbose" tar -cJp --exclude='./workspace' --exclude='./
  --exclude='./root/rpmbuild' --exclude='./root/.rpmmacros' --exclude='./root/.bash_history' --exclude='./var/tmp/*rpm' --exclude='./bin/qemu-aarch64-static' \
  --exclude='./usr/bin/qemu-aarch64-static' --exclude='./usr/bin/qemu-arm-static' --exclude='./var/lib/yum/*' --exclude='./var/cache/yum/*' -f "./rocky/image.tar.xz" -C / .
 install -m 0755 ${SDIR}/install.sh ./rocky/install.sh
+cp -a ${SDIR}/install.env ./rocky/
 
 mkdir scripts
 cat > scripts/initrd-install << EOF
@@ -277,7 +284,7 @@ echo "=================================" | tee /dev/kmsg
 echo "Installing Rocky Linux. Please wait..." | tee /dev/kmsg
 echo "=================================" | tee /dev/kmsg
 
-modprobe -a sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console nvme ${bootctl_module} 2>&1 | tee /dev/kmsg
+modprobe -a sdhci-of-dwcmshc mlxbf_tmfifo mlxbf_gige pinctrl-mlxbf3 8021q dw_mmc_bluefield mmc_block virtio_console nvme ${bootctl_module} 2>&1 | tee /dev/kmsg
 modprobe -a mlx5_ib mlxfw ib_umad 2>&1 | tee /dev/kmsg
 
 sleep 5
@@ -356,4 +363,4 @@ $mkbfb \
     ${BFB} /workspace/${BFB_FILENAME}
 cd ..
 
-echo "BFB is ready: `readlink -f /workspace/${BFB_FILENAME}`"
+echo "BFB is ready: $(readlink -f /workspace/${BFB_FILENAME})"
